# Define analysis parameters
PAIRED: false # true, false
HOST: 'HUMAN' # HUMAN, MOUSE
SUB_DEPTH: 5000000 # subsampling depth

# Define IPHOMED directory
IPHOMED: '' # IPHOMED directory

# Define Metamorpheus CMD.dll
METAMORPHEUS: '' # Metamorpheus CMD.dll

# BOWTIE2 databases
BOW_H_DB: '' # human database directory
BOW_M_DB: '' # mouse database directory

# Kraken2 database
KRAKEN_DB: '' # kraken database directory

# Bracken database
BRACKEN_DB: '' # bracken database directory

# UNIPROT databases
UNIPROT_H_DB: '' # human uniprot fasta
UNIPROT_M_DB: '' # mouse uniprot fasta
UNIPROT_CRAP_DB: '' # contamination uniprot fasta
